# Generated by Django 2.2.7 on 2019-11-30 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191130_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovid',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bovid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bovids', to='core.Bovid')),
            ],
        ),
    ]
