# Generated by Django 2.2.7 on 2019-12-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191201_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovid',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
