# Generated by Django 2.2.7 on 2019-12-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bovid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeevent',
            name='bovid',
        ),
        migrations.AddField(
            model_name='bovid',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.LifeEvent'),
            preserve_default=False,
        ),
    ]
