# Generated by Django 2.2.7 on 2019-12-04 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191203_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bovid',
            name='events',
        ),
        migrations.AddField(
            model_name='bovid',
            name='events',
            field=models.ManyToManyField(blank=True, to='core.LifeEvent'),
        ),
    ]
