# Generated by Django 2.2.7 on 2019-12-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191204_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bovid',
            name='events',
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='bovid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Bovid'),
            preserve_default=False,
        ),
    ]
