# Generated by Django 2.2.8 on 2019-12-08 20:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191206_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovid',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.bovid_image_file_path),
        ),
        migrations.AlterField(
            model_name='bovid',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
